language: node_js
node_js:
  - '6'
  - '8'

cache:
  directories:
    - "node_modules"

before_script:
  - npm run lint

after_success:
  - npm run coverage

notifications:
  email:
    on_success: never

jobs:
  node_js:
    - '6'
    - '8'
  allow_failures:
    - stage: integration tests
  include:
    - stage: integration tests
      script: npm run integrationTests
      if: (branch = dev) AND (type IS cron)
